### ISSUE TITLE
Fallo de funcionamiento

### ISSUE THREAD

**Issue by emoreno-94** [Ciclop/Terasology#102]
Terasology dejo de funcionar después de commit https://github.com/Ciclop/Terasology/commit/129ecd87441733d2a2b063bb929e214d8b40e926

**Comment by Phfollert** [comment]
Disculpa, el error lo comete un archivo refactorizado por mi compañero. Lo arreglo ahora

**Comment by Phfollert** [comment]
Creo que ya está arreglado, avisa para cerrar.

**Comment by emoreno-94** [comment]
ya funciona c:
