### ISSUE TITLE
Terasology no buildea

### ISSUE THREAD

**Issue by emoreno-94** [Ciclop/Terasology#116]
Al ejecutar "./gradlew build" en terasology este falla, segun lo que marca el error se debe a modo fly

![image](https://cloud.githubusercontent.com/assets/10638887/9216944/93f501d4-4097-11e5-9e08-dce78e1d9598.png)

**Comment by FrancoPinoC** [comment]
No tiene que ver con que use cosas de CodeCity sin declararlo como dependencia en el module.txt (como nos pasó cuando estabamos probando cosas entre Coloring y los análisis)?

**Comment by elarielcl** [comment]
Sip, arreglado en https://github.com/Ciclop/Terasology/commit/2655ddda4d58b367e50e4a5ec4c85f4f31a798b5
También hice un merge del cambio en Coloreo en https://github.com/Ciclop/Terasology/commit/6271a16dc76a14ea331f6dcc8c85ad05fc0a6526 para que podamos seguir trabajando normalmente ahí
