### ISSUE TITLE
RS10 - Ejecutar análisis y generar cambios del coloreo desde la consola de Terasology

### ISSUE THREAD

**Issue by elarielcl** [Ciclop/Terasology#38]
Agregar comando a la consola de Terasology con el cual se  llame el procedimiento de análisis de código y se llame el procedimiento que ejecute el respectivo coloreo

**Comment by elarielcl** [comment]
Concept Location :
- Sección ConsoleCommands del README del proyecto original : Se averiguó como abrir la consola en el juego y ejecutar los comandos.
  - FileSearch de eclipse buscando"teleport"
    - PlayerSystem : Clase tiene el método teleport que tiene la anotación @Command
      - Command, anotación para comandos de consola , ubicado en org.terasology.logic.console
        - Subpaquetes relacionados : commands, commandSystem.adapter, commandSystem.annotations, commandSystem.exceptions, suggesters, ui

**Comment by elarielcl** [comment]
Concept Location :
- Se llegó a org.terasology.logic.console.command.CoreCommand, a través FiliSearch de eclipse buscando "help"
  - Métodos getCommands y getCommand retornan ConsoleCommand /s
    - Con Open Call Hierarchy de eclipse sobre ConsoleCommand se encontró el método registerCommand en Console que es una interfaz con implementación ConsoleImpl. El método usa registerAvailable de MethodCommand, que usa reflexión para registrar los comandos que tengan la anotación @Command .

**Comment by elarielcl** [comment]
Para aprender a crear comandos de consola se puede visitar : https://github.com/MovingBlocks/Terasology/wiki/Console-Commands#creating-your-own-console-commands

**Comment by emoreno-94** [comment]
Se creó una interface genérica para los coloreos llamada IColoring la cual posee la clase abstracta AbstractColoring de la cual heredan estos.
Ya que AbstractColoring es un template, basta que se sobreescriban los siguientes métodos:
- getDataColoring() :aquí se deben preocupar de guardar sus datos del análisis de la métrica
- getColor(String path): aquí deben retornar el color correspondiente a la clase de ruta "path"

Cabe destacar que la clase tiene el atributo "params" el cual es del tipo String[], en este deben poner los parámetros necesarios para que puedan ejecutar sus métricas (este es seteado con execute, ver más abajo).

Con esto implementado basta ejecutar lo siguiente para que la métrica correspondiente haga su coloreo:

<pre>
IColoring coloring = new ("Metrica")Coloreo();
coloring.execute(params);
</pre>

Por ejemplo, para CheckStyle:

<pre>
IColoring c = new CheckStyleColoring();
c.execute(params);
</pre>

Finalmente se creo una clase para cada métrica (ver en modulo Coloring, package coloring) donde pueden hacer lo ya mencionado. Además también se creo la clase ColoringCommands en la cual deben poner su comando de coloreo, por el momento está en el mismo package anterrior.
