### ISSUE TITLE
RS13 - Colorear un bloque desde consola de Terasology

### ISSUE THREAD

**Issue by elarielcl** [Ciclop/Terasology#41]
Desde la consola de Terasology debe ser posible elegir un bloque específico y colorearlo con un color fijo

**Comment by seanorar** [comment]
#20

**Comment by seanorar** [comment]
#20

**Comment by elarielcl** [comment]
- Se crea nueva branch, para investigar el coloreo de los bloques Coloring https://github.com/Ciclop/Terasology/tree/Coloring

**Comment by elarielcl** [comment]
- Viendo:
  - El bloque creado por el equipo jeditint
  - La wiki : https://github.com/MovingBlocks/Terasology/wiki/Tutorial:-How-to-make-blocks-with-custom-UI
- Se construyeron bloques Coloring:Blue, Coloring:Green y Coloring:Red con "tiles" simples de los colores respectivos
- Trabajo realizado junto a(agreguense si se me olvidó alguien):
  - https://github.com/seanorar 
  - https://github.com/Ciclop 
- Commit: https://github.com/Ciclop/Terasology/commit/aaac1c80a96b957cbf2f97226bc52398cd7e22c8

**Comment by elarielcl** [comment]
- Siguiendo la recomendación del equipo CodeCover(nombre no final) se estudió el comando placeBlock de la clase BlockCommand, y se escribió el comando placeColorBlock en el módulo Coloring con la misma funcionalidad pero que solo crea los bloques creados en el comentario anterior. Commit:https://github.com/Ciclop/Terasology/commit/ad134fa86e1b27fe044f85cfc8bbea6f6e242b3d
- El comando placeColorBlock arrojaba el error "Permission denied" para la clase WorldRenderer, por lo que se agregó está al sandbox de seguridad. Commit:https://github.com/Ciclop/Terasology/commit/acfde5cedd6ee0ec84a34c1236f076160a9939ae
