### ISSUE TITLE
RS14 - Colorear un conjunto de bloques desde consola de Terasology

### ISSUE THREAD

**Issue by elarielcl** [Ciclop/Terasology#42]
Desde la consola de Terasology debe ser posible elegir un conjunto de bloques específico y colorearlos con un color fijo

**Comment by seanorar** [comment]
se implemento el comando PlaceColorBuilding el cual permite crear un edificio de color en una determinada posición y altura 
ac3eb417062a9d79f0af869c732193a4afc20b1b
