### ISSUE TITLE
RS19 - Investigar tipo de integración PMD

### ISSUE THREAD

**Issue by elarielcl** [Ciclop/Terasology#47]
Investigar proyecto pmd.sourceforge.net/ y factibilidad de alguna de las siguientes opciones para integrar en este proyecto :
- Llamar a PMD desde Terasology
- Adaptar parte del código de PMD en Terasology
- Escribir las características de  PMD desde cero en Terasology

**Comment by elarielcl** [comment]
- Fork de código fuente de pmd en: https://github.com/sking32/pmd
- Descarga código fuente pmd desde fork anterior en eclipse

**Comment by elarielcl** [comment]
- Localización de Conceptos:
  - Búsqueda "File Search" de eclipse buscando "commandline" en el proyecto pmd se encontró la clase PMDCommandLineInterface.
  - Al hacer un "OpenCallHierarchy" de PMDCommandLineInterface se encontró PMD que contiene el main del proyecto que se ejecuta al llamar a PMD desde la consola.
  - En PMD se encontró el método doPMD el cual setea el Writer del output de pmd(a través de un Renderer), el que puede ser un archivo o la salida estándar.

**Comment by sking32** [comment]
- Llamada exitosa de PMDdesde Terasology llamando a la consola y ejecutando comando desde la consola.
- Intento fallido de agregar y usar las librerías de PMD al proyecto de Terasology, el juego se cierra retornando un error: "AL lib: alc_cleanup: 1 device not closed"

**Comment by elarielcl** [comment]
- Llamada exitosa de PMD desde Terasology llamando a la consola y ejecutando comando desde la consola.
- Intento fallido de agregar los archivos .jar de PMD a terasology y llamar PMD.main(args), el juego se cierra retornando un error: "AL lib: alc_cleanup: 1 device not closed"

**Comment by elarielcl** [comment]
Se decide hacer llamada desde terminal a .jar de pmd.
