### ISSUE TITLE
RS20 - Implementar integración PMD

### ISSUE THREAD

**Issue by elarielcl** [Ciclop/Terasology#48]
Implementar integración dependiendo de la decisión tomada en #47 , agregar las clases necesarias para este propósito

**Comment by sking32** [comment]
- Llamada exitosa de PMD desde Terasology llamando a la consola y ejecutando comando desde la consola.
- Intento fallido de agregar y usar las librerías de PMD al proyecto de Terasology, el juego se cierra retornando un error: "AL lib: alc_cleanup: 1 device not closed"

**Comment by elarielcl** [comment]
Implementado en el módulo PMDColoring, en la clase PMDProcessor
métodos invokePMD y buildInputString, con llamadas desde terminal a .jar de pmd
