### ISSUE TITLE
RS26 - Implementación de un botón para el llamado a modo Fly

### ISSUE THREAD

**Issue by criparra** [Ciclop/Terasology#54]
Se pretende una implementación amigable para el usuario por medio de un botón que pueda ingresar directamente al modo fly. Se considera además, una alternativa la cual sería implementar dicho modo usando la consola del juego.

**Comment by Cervator** [comment]
Hi guys.

Sure are a lot of issues and comments flying around in this repo, you got me curious about what you're trying to do :-)

This one stuck out as there is already a module that'll add a "Fly mode" button: https://github.com/Terasology/FlightModeToggleButton (although I'm not sure it currently works)

If you're writing code somewhere feel free to take inspiration from that module. Any other questions just ask - Google Translate FTW! ;-)

(For instance we already have Checkstyle, PMD, etc - so I'm not sure what you're trying to do differently)

**Comment by elarielcl** [comment]
Hi Cervator,
We are a group of, University of Chile's students in fourth year. We are taking the Software Engineering course where students have to develop a project. Our project consists on using/adapting terasology for creating software visualization such as Codecity's (http://www.inf.usi.ch/phd/wettel/codecity.html).
So, the idea is to take a java project and with terasology generate its code/city visualization.
In addition we want to have a quick access to fly-mode to see the city from different perspectives. And finally, we  want to paint the project cities' according to different code analizers(PMD, CheckStyle, CodeCover, info from GitHub).
That is our project, thanks for the FlightModeToggleButton, it will be really helpful. If you have any other suggestion to any part of the project, please say us.

**Comment by Cervator** [comment]
Very nice! Makes so much more sense now, and that's a very cool project. Best of luck! Let me know if you run into any questions :-)

I actually wrote up a big suggestion a while back that's somewhat similar: generating a world and indeed a city to represent the state of various areas of the engine + modules. Complete with ideas about taking code analytics, issue counts from GitHub, and so on, and representing it with creatures in-game in the city. It is a long read but it might give some more inspiration:

http://forum.terasology.org/threads/the-world-of-varied-and-noteworthy-achievements.1209/

Not to mention that if you get this working we'd love to have a version for the Terasology project itself and our libraries + modules :-) Maybe that'll be a nice bonus to present as part of your project!

Finally, fun fact: my wife's family is originally from Santiago. ¡Buena suerte!

**Comment by Cervator** [comment]
Oh, and if you haven't spotted it yet, here's our world gen tutorial: https://github.com/Terasology/TutorialWorldGeneration/wiki

**Comment by fdns** [comment]
Hi Cervator,
Thanks for all the information, we didn't see that tutorial so it will help us alot to understand the World Generation. We don't have a lot of time to make this work perfectly, but i think we have enough people to pull it off.

You will have the city of Terasology project, so don't worry!

**Comment by Cervator** [comment]
Awesome! Looking forward to it :-)

Feel free to use our forum and IRC for any assistance needed. We're a friendly bunch.
