### ISSUE TITLE
Investigar tipo de integración CheckStyle

### ISSUE THREAD

**Issue by emoreno-94** [Ciclop/Terasology#60]
Investigar proyecto http://checkstyle.sourceforge.net/ y factibilidad de alguna de las siguientes opciones para integrar en este proyecto :

-Llamar a CheckStyle desde Terasology
-Adaptar parte del código de CheckStyle en Terasology
-Escribir las características de CheckStyle desde cero en Terasology

**Comment by emoreno-94** [comment]
Se descargó el plugin CheckStyle para eclipse y se realizaron varias pruebas para comprobar su funcionamiento, las cuales incluyeron analizar 2 métricas:
- Complejidad ciclomática: medida de la complejidad lógica de un programa a partir de la representación del diagrama de flujo asociado.
- Complejidad de expresiones booleanas: Revisa la cantidad de operadores booleanos que se encuentran en las condiciones, por ejemplo en los if, while,  for, etc.

**Comment by emoreno-94** [comment]
Se descargó el código de Checkstyle desde github para revisarlo

**Comment by emoreno-94** [comment]
Después de una pequeña búsqueda se encontró la clase principal, pero aun no se realizan pruebas mayores para comprobar su funcionamiento.

**Comment by seanorar** [comment]
Utilizando el plugin de checkstyle, se encontró el archivo xml que genera la configuración de la métrica.

**Comment by seanorar** [comment]
Se crearon dos archivos xml uno para cada métrica (booleana y ciclomatica) los cuales son utilizados para arrancar la aplicación desde la consola

**Comment by seanorar** [comment]
El resultado del análisis queda guardado en un archivo de texto plano.

**Comment by seanorar** [comment]
Integrar el código de checkstyle generaba problemas al realizar build del proyecto, por esta razón se investigara como realizar la integración sin que se vea modificado el build del juego.
