### ISSUE TITLE
RS33: Implementar integración CheckStyle

### ISSUE THREAD

**Issue by emoreno-94** [Ciclop/Terasology#61]
Implementar integración dependiendo de la decisión tomada en #60  , agregar las clases necesarias para este propósito.

**Comment by seanorar** [comment]
el resultado de analizar un archivo mediante checkstyle desde terasology, genera un documento xml que contiene el resultado

**Comment by emoreno-94** [comment]
Con lo dicho en #60 finalmente se opto por integrar Checkstyle con la ayuda de su .jar el cual fue descargado de su misma página.

**Comment by emoreno-94** [comment]
Se creó una carpeta la cual almacena la información necesaria para una correcta ejecución (archivo de entrada, métrica a utilizar y .jar de CheckStyle)

**Comment by emoreno-94** [comment]
Con ayuda de un tutorial para la creación de comandos, se creo el comando "cstyle" el cual recibe de argumento el archivo de entrada, la métrica a utilizar y un valor para la métrica seleccionada. Cabe destacar que el resultado de este analisis  se guarda en un archivo .xml
