### ISSUE TITLE
RS46 Investigar API GitHub

### ISSUE THREAD

**Issue by mperalta92** [Ciclop/Terasology#76]
Investigar Sobre GitHub y la API (https://developer.github.com) que permita 
-Verificar si existe un repositorio github de un proyecto
-Obtener métricas "bugs" y "versiones"

**Comment by kidonkey** [comment]
Específicamente para utilizar la API de GitHub (que en realidad no se usó) fueron descargadas 2 librerías para poder implementar la adquisición de datos remotos: JSch [1] para permitir la transferencia de datos y JGit [2], una librería con clases y métodos para interactuar con estructuras git.

Esta decisión se tomó debido a que la API de GitHub no prestaba las funciones específicas que necesitábamos obtener información de los repositorios y era difícil manejarla desde el juego.  

[1] http://www.jcraft.com/jsch/
[2] https://eclipse.org/jgit/
