### ISSUE TITLE
RS47: Implementar métricas GitHub

### ISSUE THREAD

**Issue by mperalta92** [Ciclop/Terasology#79]
Implementar integración dependiendo de la información en #76 , agregar las clases necesarias para este propósito. Esto sin necesidad de obtener la referencia al repositorio cuando se importa el proyecto desde JEdit #

**Comment by kidonkey** [comment]
Bug metric and Version metric were implemented. Both were integrated into GitColoring at the Coloring module.
As of now, Bug metric should paint a block from a class with reported bugs red, in a world map WorldCodeCity style.
Version Metric paints the blocks from every class green, yellow or red, depending on the extent of its change history.
