### ISSUE TITLE
Problema al hacer run de terasology

### ISSUE THREAD

**Issue by emoreno-94** [Ciclop/Terasology#95]
Mientras hacia merge de mi rama me di cuenta que anteriormente el juego no se ejecutaba, es decir, al realizar el tipico proceso de build, compileJava y run todo funcionaba pero al crear una partida se queda pegado mientras carga con el mensaje "Awaiting Character Spawn...", creo que deben revisar cual es el commit que hizo eso y arreglarlo para seguir trabajando normalmente en el master.

PD: Uso Ubuntu y tengo java 8

**Comment by elarielcl** [comment]
Tengo el mismo problema, y me falla desde este https://github.com/Ciclop/Terasology/commit/d0cd38a0454cff7d5d8ea704bec9d0d0df7964a3 commit

**Comment by fdns** [comment]
Aca tengo el link de los test que no pasan. @xAlstrat 
[Tests](https://github.com/Ciclop/Terasology/blob/master/engine-tests/src/test/java/org/terasology/world/generation/WorldBuilderTest.java)

**Comment by emoreno-94** [comment]
resuelto con #96
